#this is the name of the service
service: gabriel-money-api

provider:
  name: aws
  runtime: nodejs18.x  # this is the latest Node.js version
  region: us-east-1
  memorySize: 128  # tweaks memory size based on API needs
  timeout: 10
  environment:
    MONGO_URI: "${env:MONGO_URI}"  # MongoDB connection string from .env

functions:
  api:
    handler: server.handler  # matches the export from server.js
    events:
      - http:
          path: /{proxy+}  # catch-all route for API Gateway
          method: any  # support all HTTP methods

plugins:
  - serverless-offline  # enables local testing

custom:
  serverless-offline:
    httpPort: 3000
